apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: {{.Release.Namespace}}
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: "ghcr.io/nfacha/planealertapi:master"
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: /app/config.json
              name: plane-alert-config
              subPath: config.json
      volumes:
        - name: plane-alert-config
          configMap:
            name: plane-alert-config
