version: '3'

services:
  postgres:
    image: postgres
    restart: unless-stopped
    ports:
      - "9688:5432"
    env_file:
      - pg.env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - pgadmin.env
    ports:
      - "8574:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

  planealert:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - postgres
    restart: unless-stopped

  api:
    restart: unless-stopped
    build:
      context: ../PlaneAlertAPI
      dockerfile: Dockerfile
    volumes:
      - ../PlaneAlertAPI/:/app
    ports:
      - "8599:3000"
    depends_on:
      - postgres
    labels:
      - traefik.enable=true
      - traefik.http.routers.api.rule=Host(`api.plane-alert.facha.dev`)
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.entrypoints=https
      - traefik.http.routers.api.tls.certresolver=certresolver


volumes:
  postgres-data:
  pgadmin-data:
