version: '3'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - pg.env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - pgadmin.env
    ports:
      - "8888:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

  planealert:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - postgres
volumes:
  postgres-data:
  pgadmin-data:
